#!/usr/bin/env zsh

fpath=(~/.zfunctions $fpath)
autoload -U \
				 new_project \
				 start_project \
				 emacs_update_deps \
				 emacs_shutdown_servers \
				 start_download_server \
				 start_ui_server \
				 index_libraries \
				 recoll
