#!/usr/bin/env zsh
# recoll <library> <x display>

[[ -n $2 ]] && export DISPLAY=:$2
export RECOLL_CONFDIR=/media/Erudite/Indexes/$1
[[ -d $RECOLL_CONFDIR ]] || mkdir -p $RECOLL_CONFDIR
/usr/bin/recoll &> /dev/null &
