#!/usr/bin/env zsh
# Additional user tools go here.

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

export EDITOR="emacsclient -s projects -c"
export VISUAL=$EDITOR

#emacs cask
export PATH="$HOME/.cask/bin:$PATH"

#set up pyenv evironment
export PYENV_ROOT=/usr/local/pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#set up rvm environment
# RVMSCRIPT="/usr/local/rvm/scripts/rvm"
# if [ -s $RVMSCRIPT ] ; then
#    source $RVMSCRIPT
# fi
